import { DataSource } from 'typeorm'

import { env } from '../../env'
import { Product } from '../../entities/product.entity'
import { Category } from '../../entities/category.entity'
import { ProductAutoGeneratedUUID1782952869448 } from './migrations/1782952869448-ProductAutoGeneratedUUID'

export const appDataSource = new DataSource({
  type: 'postgres',
  host: env.DATABASE_HOST,
  port: env.DATABASE_PORT,
  username: env.DATABASE_USER,
  password: env.DATABASE_PASSWORD,
  database: env.DATABASE_NAME,
  entities: [Product, Category],
  migrations: [ProductAutoGeneratedUUID1782952869448],
  logging: env.NODE_ENV === 'development',
})

appDataSource
  .initialize()
  .then(() => {
    console.log('Database with typeorm connected!')
  })
  .catch((err) => {
    console.error('Error during Data Source initialization', err)
  })
